// Page « Mes disponibilités » du Coach (UKAN V2)
// Interface de gestion des disponibilités hebdomadaires + exceptions de dates.
// Données conservées en mémoire de session (mode démo, comme le reste de l'app).
// Ouverte depuis : Avancé → Passer en mode Coach → Dashboard Coach → Mes Dispos.
// ignore_for_file: annotate_overrides, curly_braces_in_flow_control_structures, deprecated_member_use

import 'package:flutter/material.dart';
import 'appointment_models.dart';
import 'appointments_repository.dart';

const cream=Color(0xfff8f6f1), ink=Color(0xff252321), muted=Color(0xff8d8a86), gold=Color(0xffeda900), green=Color(0xff176b50), red=Color(0xffff555d);

class CoachAvailabilityPage extends StatefulWidget {
  final String coachId;
  const CoachAvailabilityPage({super.key, this.coachId = 'coach_1'});
  State<CoachAvailabilityPage> createState()=>_CoachAvailabilityPageState();
}

class _CoachAvailabilityPageState extends State<CoachAvailabilityPage> with SingleTickerProviderStateMixin {
  late final TabController tabs;
  final _repo=AppointmentsRepository();
  late List<DayAvailability> days;
  late List<AvailabilityException> exceptions;
  final expanded=<String>{'2026-08','2026-09'};
  void initState(){super.initState();tabs=TabController(length:2,vsync:this);days=_repo.getOrCreateWeekly(widget.coachId).map((d)=>d.copy()).toList();exceptions=_repo.getAvailabilityExceptions(widget.coachId).map((e)=>e.copy()).toList();}
  void dispose(){tabs.dispose();super.dispose();}
  void _persistWeek()=>_repo.setWeeklyAvailability(widget.coachId,days);
  void _persistExceptions()=>_repo.setAvailabilityExceptions(widget.coachId,exceptions);
  void msg(String s){ScaffoldMessenger.of(context)..hideCurrentSnackBar()..showSnackBar(SnackBar(content:Text(s),behavior:SnackBarBehavior.floating));}

  Future<void> editDay(int i) async {
    final r=await showModalBottomSheet<DayResult>(context:context,isScrollControlled:true,useSafeArea:true,backgroundColor:cream,shape:const RoundedRectangleBorder(borderRadius:BorderRadius.vertical(top:Radius.circular(28))),builder:(_)=>DaySheet(day:days[i].copy()));
    if(r==null||!mounted)return;
    setState((){days[i]=r.day;for(final x in r.targets)days[x]=DayAvailability(days[x].name,r.day.ranges.map((e)=>e.copy()).toList(),enabled:r.day.enabled);});_persistWeek();msg('Horaires enregistrés');
  }
  Future<void> editException([AvailabilityException? old]) async {
    final r=await showModalBottomSheet<AvailabilityException>(context:context,isScrollControlled:true,useSafeArea:true,backgroundColor:cream,shape:const RoundedRectangleBorder(borderRadius:BorderRadius.vertical(top:Radius.circular(28))),builder:(_)=>ExceptionSheet(value:old?.copy()));
    if(r==null||!mounted)return;setState((){if(old==null){r.id=exceptions.fold(0,(m,e)=>e.id>m?e.id:m)+1;exceptions.add(r);}else{r.id=old.id;exceptions[exceptions.indexWhere((e)=>e.id==old.id)]=r;}exceptions.sort((a,b)=>a.start.compareTo(b.start));expanded.add(monthKey(r.start));});_persistExceptions();msg(old==null?'Exception ajoutée':'Exception modifiée');
  }
  Future<void> remove(AvailabilityException e) async {final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Supprimer cette exception ?'),content:const Text('Cette action est définitive pour la session.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Annuler')),FilledButton(onPressed:()=>Navigator.pop(c,true),style:FilledButton.styleFrom(backgroundColor:red),child:const Text('Supprimer'))]));if(ok==true&&mounted){setState(()=>exceptions.remove(e));_persistExceptions();msg('Exception supprimée');}}

  Widget build(BuildContext context)=>Scaffold(backgroundColor:cream,appBar:AppBar(backgroundColor:cream,surfaceTintColor:Colors.transparent,centerTitle:true,title:const Text('Mes disponibilités',style:TextStyle(fontWeight:FontWeight.w800,fontSize:19)),actions:[IconButton(onPressed:()=>msg('Disponibilités conservées pour cette session'),icon:const Icon(Icons.check_circle_outline,color:gold))],bottom:TabBar(controller:tabs,labelColor:ink,unselectedLabelColor:muted,indicatorColor:gold,indicatorWeight:3,tabs:const [Tab(text:'Semaine'),Tab(text:'Exceptions')])),body:SafeArea(top:false,child:TabBarView(controller:tabs,children:[week(),exceptionTab()])));
  Widget week()=>ListView(padding:const EdgeInsets.all(16),children:[const Heading('Votre semaine','Appuyez sur un jour pour le modifier'),const SizedBox(height:12),...List.generate(7,(i)=>Padding(padding:const EdgeInsets.only(bottom:10),child:CardBox(child:InkWell(onTap:()=>editDay(i),child:Padding(padding:const EdgeInsets.all(15),child:Row(children:[Container(width:10,height:10,decoration:BoxDecoration(shape:BoxShape.circle,color:days[i].enabled?green:red)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(days[i].name,style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:5),Text(days[i].summary,style:const TextStyle(color:muted,fontSize:13))])),const Icon(Icons.chevron_right,color:muted)]))))))]);
  Widget exceptionTab(){final map=<String,List<AvailabilityException>>{};for(final e in exceptions)map.putIfAbsent(monthKey(e.start),()=>[]).add(e);return ListView(padding:const EdgeInsets.all(16),children:[Row(children:[const Expanded(child:Heading('Exceptions de dates','Vacances et horaires particuliers')),FilledButton.icon(onPressed:editException,style:FilledButton.styleFrom(backgroundColor:gold,foregroundColor:ink),icon:const Icon(Icons.add),label:const Text('Ajouter'))]),const SizedBox(height:16),if(map.isEmpty)const CardBox(child:Padding(padding:EdgeInsets.all(30),child:Center(child:Text('Aucune exception enregistrée')))) else ...map.entries.map((g){final open=expanded.contains(g.key);return Padding(padding:const EdgeInsets.only(bottom:12),child:CardBox(child:Column(children:[ListTile(leading:const Icon(Icons.calendar_month_outlined,color:green),title:Text('${monthLabel(g.value.first.start)} — ${g.value.length} exception${g.value.length>1?'s':''}',style:const TextStyle(fontWeight:FontWeight.w800)),trailing:Icon(open?Icons.expand_less:Icons.expand_more),onTap:()=>setState(()=>open?expanded.remove(g.key):expanded.add(g.key))),if(open)...g.value.map((e)=>Container(decoration:const BoxDecoration(border:Border(top:BorderSide(color:Color(0xffebe7df)))),child:ListTile(title:Text(e.dateLabel,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${e.kind.label}${e.allDay?' · Journée complète':' · ${e.ranges.map((x)=>x.label).join(' · ')}'}${e.reason.isEmpty?'':'\n${e.reason}'}'),isThreeLine:e.reason.isNotEmpty,trailing:PopupMenuButton<String>(onSelected:(x)=>x=='edit'?editException(e):remove(e),itemBuilder:(_)=>const [PopupMenuItem(value:'edit',child:Text('Modifier')),PopupMenuItem(value:'remove',child:Text('Supprimer'))]))))])));})]);}
}

class DaySheet extends StatefulWidget {const DaySheet({super.key,required this.day});final DayAvailability day;State<DaySheet> createState()=>_DaySheetState();}
class _DaySheetState extends State<DaySheet>{late DayAvailability day;final targets=<int>{};String? error;static const names=['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'];void initState(){super.initState();day=widget.day;}
  Future<void> pick(int i,bool start)async{final r=day.ranges[i],p=await showTimePicker(context:context,initialTime:start?r.start:r.end,helpText:start?'Heure de début':'Heure de fin');if(p!=null)setState(()=>day.ranges[i]=start?r.withStart(p):r.withEnd(p));}
  String? validate(){if(!day.enabled)return null;if(day.ranges.isEmpty)return'Ajoutez au moins un créneau.';final s=[...day.ranges]..sort((a,b)=>a.begin.compareTo(b.begin));for(var i=0;i<s.length;i++){if(s[i].finish<=s[i].begin)return'L’heure de fin doit être postérieure au début.';if(i>0&&s[i].begin<s[i-1].finish)return'Deux créneaux se chevauchent.';}day.ranges=s;return null;}
  Future<void> copyTo()async{final local={...targets},r=await showDialog<Set<int>>(context:context,builder:(c)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('Copier vers'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:List.generate(7,(i)=>CheckboxListTile(value:local.contains(i),title:Text(names[i]),onChanged:(v)=>set(()=>v==true?local.add(i):local.remove(i)))))),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Annuler')),FilledButton(onPressed:()=>Navigator.pop(c,local),child:const Text('Confirmer'))])));if(r!=null)setState((){targets..clear()..addAll(r);});}
  Widget build(BuildContext context)=>SheetFrame(child:(controller)=>ListView(controller:controller,padding:const EdgeInsets.fromLTRB(18,8,18,28),children:[const Handle(),Row(children:[Expanded(child:Text('Modifier ${day.name.toLowerCase()}',style:const TextStyle(fontSize:21,fontWeight:FontWeight.w800))),IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.close))]),CardBox(child:SwitchListTile(value:day.enabled,activeColor:green,title:const Text('Disponible',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:const Text('Activez les horaires de cette journée'),onChanged:(v)=>setState((){day.enabled=v;if(v&&day.ranges.isEmpty)day.ranges.add(TimeRange(9,0,17,0));}))),const SizedBox(height:14),if(day.enabled)...[...List.generate(day.ranges.length,(i)=>TimeRow(range:day.ranges[i],start:()=>pick(i,true),end:()=>pick(i,false),remove:()=>setState(()=>day.ranges.removeAt(i)))),TextButton.icon(onPressed:()=>setState(()=>day.ranges.add(TimeRange(9,0,17,0))),icon:const Icon(Icons.add),label:const Text('Ajouter un créneau'))],if(error!=null)Text(error!,style:const TextStyle(color:red,fontWeight:FontWeight.w700)),OutlinedButton.icon(onPressed:copyTo,icon:const Icon(Icons.copy_outlined),label:Text(targets.isEmpty?'Copier vers d’autres jours':'Copie vers ${targets.length} jour(s)')),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>Navigator.pop(context),child:const Text('Annuler'))),const SizedBox(width:10),Expanded(child:FilledButton(style:FilledButton.styleFrom(backgroundColor:gold,foregroundColor:ink),onPressed:(){final e=validate();if(e!=null){setState(()=>error=e);return;}Navigator.pop(context,DayResult(day,targets));},child:const Text('Enregistrer')))])]));}

class ExceptionSheet extends StatefulWidget{const ExceptionSheet({super.key,this.value});final AvailabilityException? value;State<ExceptionSheet> createState()=>_ExceptionSheetState();}
class _ExceptionSheetState extends State<ExceptionSheet>{late AvailabilityException value;late bool period;late final TextEditingController reason;String? error;void initState(){super.initState();value=widget.value??AvailabilityException(0,DateTime.now(),kind:ExceptionKind.unavailable,allDay:true);period=value.end!=null;reason=TextEditingController(text:value.reason);}void dispose(){reason.dispose();super.dispose();}
  Future<void> date(bool end)async{final initial=end?(value.end??value.start):value.start,p=await showDatePicker(context:context,initialDate:initial,firstDate:DateTime(2020),lastDate:DateTime(2100),helpText:end?'Date de fin':'Date de début');if(p!=null)setState((){if(end)value.end=p;else value.start=p;});}
  Future<void> time(int i,bool start)async{final r=value.ranges[i],p=await showTimePicker(context:context,initialTime:start?r.start:r.end);if(p!=null)setState(()=>value.ranges[i]=start?r.withStart(p):r.withEnd(p));}
  String? validate(){if(period&&value.end!.isBefore(value.start))return'La date de fin précède la date de début.';if(!value.allDay){if(value.ranges.isEmpty)return'Ajoutez au moins un créneau.';final s=[...value.ranges]..sort((a,b)=>a.begin.compareTo(b.begin));for(var i=0;i<s.length;i++){if(s[i].finish<=s[i].begin)return'L’heure de fin doit être postérieure au début.';if(i>0&&s[i].begin<s[i-1].finish)return'Deux créneaux se chevauchent.';}value.ranges=s;}return null;}
  Widget build(BuildContext context)=>SheetFrame(initial:.9,child:(controller)=>ListView(controller:controller,padding:const EdgeInsets.fromLTRB(18,8,18,28),children:[const Handle(),Row(children:[Expanded(child:Text(widget.value==null?'Ajouter une exception':'Modifier l’exception',style:const TextStyle(fontSize:21,fontWeight:FontWeight.w800))),IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.close))]),const Label('Type d’exception'),DropdownButtonFormField<ExceptionKind>(value:value.kind,decoration:input(),items:ExceptionKind.values.map((e)=>DropdownMenuItem(value:e,child:Text(e.label))).toList(),onChanged:(e)=>setState(()=>value.kind=e!)),const Label('Durée'),SegmentedButton<bool>(segments:const [ButtonSegment(value:false,label:Text('Date unique')),ButtonSegment(value:true,label:Text('Période'))],selected:{period},onSelectionChanged:(s)=>setState((){period=s.first;value.end=period?value.start:null;})),const Label('Date de début'),PickField(text:fullDate(value.start),icon:Icons.calendar_today_outlined,onTap:()=>date(false)),if(period)...[const Label('Date de fin'),PickField(text:fullDate(value.end??value.start),icon:Icons.event_available_outlined,onTap:()=>date(true))],const Label('Horaires'),SwitchListTile(contentPadding:EdgeInsets.zero,value:value.allDay,activeColor:green,title:const Text('Journée complète',style:TextStyle(fontWeight:FontWeight.w700)),onChanged:(v)=>setState((){value.allDay=v;if(!v&&value.ranges.isEmpty)value.ranges.add(TimeRange(9,0,17,0));})),if(!value.allDay)...[...List.generate(value.ranges.length,(i)=>TimeRow(range:value.ranges[i],start:()=>time(i,true),end:()=>time(i,false),remove:()=>setState(()=>value.ranges.removeAt(i)))),TextButton.icon(onPressed:()=>setState(()=>value.ranges.add(TimeRange(9,0,17,0))),icon:const Icon(Icons.add),label:const Text('Ajouter un créneau'))],const Label('Titre ou motif facultatif'),TextField(controller:reason,textCapitalization:TextCapitalization.sentences,decoration:input(hint:'Ex. vacances, formation…')),if(error!=null)Padding(padding:const EdgeInsets.only(top:10),child:Text(error!,style:const TextStyle(color:red,fontWeight:FontWeight.w700))),const SizedBox(height:18),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>Navigator.pop(context),child:const Text('Annuler'))),const SizedBox(width:10),Expanded(child:FilledButton(style:FilledButton.styleFrom(backgroundColor:gold,foregroundColor:ink),onPressed:(){final e=validate();if(e!=null){setState(()=>error=e);return;}value.reason=reason.text.trim();value.end=period?value.end:null;Navigator.pop(context,value);},child:const Text('Enregistrer')))])]));}

class SheetFrame extends StatelessWidget{const SheetFrame({super.key,required this.child,this.initial=.82});final double initial;final Widget Function(ScrollController) child;Widget build(BuildContext context)=>Padding(padding:EdgeInsets.only(bottom:MediaQuery.viewInsetsOf(context).bottom),child:DraggableScrollableSheet(expand:false,initialChildSize:initial,minChildSize:.55,maxChildSize:.97,builder:(_,c)=>child(c)));}
class TimeRow extends StatelessWidget{const TimeRow({super.key,required this.range,required this.start,required this.end,required this.remove});final TimeRange range;final VoidCallback start,end,remove;Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:9),child:Row(children:[Expanded(child:PickField(text:range.start.format(context),icon:Icons.schedule,onTap:start)),const Padding(padding:EdgeInsets.symmetric(horizontal:6),child:Text('–')),Expanded(child:PickField(text:range.end.format(context),icon:Icons.schedule,onTap:end)),IconButton(onPressed:remove,icon:const Icon(Icons.delete_outline,color:red))]));}
class PickField extends StatelessWidget{const PickField({super.key,required this.text,required this.icon,required this.onTap});final String text;final IconData icon;final VoidCallback onTap;Widget build(BuildContext context)=>InkWell(onTap:onTap,borderRadius:BorderRadius.circular(13),child:Container(padding:const EdgeInsets.symmetric(horizontal:11,vertical:13),decoration:BoxDecoration(color:Colors.white,border:Border.all(color:const Color(0xffebe7df)),borderRadius:BorderRadius.circular(13)),child:Row(children:[Icon(icon,size:16,color:green),const SizedBox(width:7),Expanded(child:Text(text,style:const TextStyle(fontWeight:FontWeight.w700)))])));}
class CardBox extends StatelessWidget{const CardBox({super.key,required this.child});final Widget child;Widget build(BuildContext context)=>Material(color:Colors.white,elevation:.5,shadowColor:Colors.black12,borderRadius:BorderRadius.circular(20),clipBehavior:Clip.antiAlias,child:child);}
class Heading extends StatelessWidget{const Heading(this.title,this.subtitle,{super.key});final String title,subtitle;Widget build(BuildContext context)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(subtitle,style:const TextStyle(color:muted,fontSize:12.5))]);}
class Label extends StatelessWidget{const Label(this.text,{super.key});final String text;Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(top:17,bottom:7),child:Text(text.toUpperCase(),style:const TextStyle(fontSize:10.5,color:muted,fontWeight:FontWeight.w800,letterSpacing:.4)));}
class Handle extends StatelessWidget{const Handle({super.key});Widget build(BuildContext context)=>Center(child:Container(width:42,height:5,margin:const EdgeInsets.only(bottom:14),decoration:BoxDecoration(color:const Color(0xffd9d4cc),borderRadius:BorderRadius.circular(3))));}
InputDecoration input({String? hint})=>InputDecoration(hintText:hint,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(13),borderSide:const BorderSide(color:Color(0xffebe7df))),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(13),borderSide:const BorderSide(color:Color(0xffebe7df))),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(13),borderSide:const BorderSide(color:gold,width:1.5)));
